sudo: required
language: java
before_install:
    - chmod +x .travis/before_test.sh
install: .travis/before_test.sh
jdk:
    - oraclejdk8
    - oraclejdk7
env:
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=80M SINGLEHOST=true
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=20M INNODB_LOG_FILE_SIZE=200M SINGLEHOST=true
    - MARIA_VERSION=5.5 MAX_ALLOWED_PACKET=40M INNODB_LOG_FILE_SIZE=400M SINGLEHOST=true
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=80M SINGLEHOST=true
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=20M INNODB_LOG_FILE_SIZE=200M SINGLEHOST=true
    - MARIA_VERSION=10.0 MAX_ALLOWED_PACKET=40M INNODB_LOG_FILE_SIZE=400M SINGLEHOST=true
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=80M SINGLEHOST=true
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=20M INNODB_LOG_FILE_SIZE=200M SINGLEHOST=true
    - MARIA_VERSION=10.1 MAX_ALLOWED_PACKET=40M INNODB_LOG_FILE_SIZE=400M SINGLEHOST=true
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=80M SINGLEHOST=true
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=20M INNODB_LOG_FILE_SIZE=200M SINGLEHOST=true
    - MYSQL_VERSION=5.7 MAX_ALLOWED_PACKET=40M INNODB_LOG_FILE_SIZE=400M SINGLEHOST=true
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=8M INNODB_LOG_FILE_SIZE=80M SINGLEHOST=true
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=20M INNODB_LOG_FILE_SIZE=200M SINGLEHOST=true
    - MYSQL_VERSION=5.6 MAX_ALLOWED_PACKET=40M INNODB_LOG_FILE_SIZE=400M SINGLEHOST=true
    - AURORA=true SINGLEHOST=false
script: mvn test -DtestSingleHost=$SINGLEHOST $ADDITIONNAL_VARIABLES -DjobId=$TRAVIS_JOB_ID -DkeystorePath="/etc/mysql/client-keystore.p12" -DkeystorePassword="kspass"
cache:
    directories:
        - $HOME/.m2
        - /var/cache/apt/archives
